//! Type Provider Infrastructure for Fusabi
//!
//! This crate provides the core infrastructure for type providers in Fusabi.
//! Type providers enable compile-time type generation from external schemas.
//!
//! # Core Components
//!
//! - `TypeProvider` trait: The main interface that all providers must implement
//! - `ProviderRegistry`: Manages registered type providers
//! - `GeneratedTypes`: Represents types generated by a provider
//! - Type definitions: `TypeDefinition`, `RecordDef`, `DuDef`, etc.
//!
//! # Example
//!
//! ```rust,ignore
//! use fusabi_type_providers::{ProviderRegistry, TypeProvider};
//! use std::sync::Arc;
//!
//! let mut registry = ProviderRegistry::new();
//! registry.register(Arc::new(MyProvider::new()));
//!
//! let types = registry.resolve(
//!     "MyProvider",
//!     "https://example.com/schema.json",
//!     "MyNamespace",
//!     &ProviderParams::default()
//! )?;
//! ```

pub mod error;
pub mod types;
pub mod generator;
pub mod provider;
pub mod registry;

// Re-export main types for convenience
pub use error::{ProviderError, ProviderResult};
pub use types::{
    TypeDefinition, RecordDef, DuDef, VariantDef, FieldDef, TypeExpr, FieldValidationResult,
};
pub use generator::{GeneratedTypes, GeneratedModule, TypeGenerator, NamingStrategy};
pub use provider::{TypeProvider, ProviderParams, Schema};
pub use registry::ProviderRegistry;
